version: '3.7'
services: 
    jupyter:
        image: jupyter/datascience-notebook:python-3.7.6
        ports:
            - 8888:8888 
        environment: 
            JUPYTER_ENABLE_LAB: "yes"
        volumes: 
            - ./:/home/jovyan/work 